tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: active
            field:
              default: true
              type: toggle
              display: Aktiv
              icon: toggle
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: name
            field:
              input_type: text
              antlers: false
              type: text
              display: Name
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: firstname
            field:
              input_type: text
              antlers: false
              type: text
              display: Vorname
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
  biography:
    display: Biografie
    sections:
      -
        display: Biografie
        instructions: 'Text, Medien hinzuf체gen'
        fields:
          -
            handle: bio_text
            field:
              buttons:
                - h2
                - bold
                - unorderedlist
                - anchor
              smart_typography: false
              save_html: false
              inline: false
              toolbar_mode: fixed
              reading_time: false
              word_count: false
              fullscreen: true
              allow_source: true
              enable_input_rules: true
              enable_paste_rules: true
              remove_empty_nodes: false
              antlers: false
              link_noopener: false
              link_noreferrer: false
              target_blank: false
              always_show_set_button: false
              collapse: false
              previews: true
              type: bard
              display: Text
              icon: bard
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: bio_media
            field:
              collapse: false
              previews: true
              fullscreen: true
              sets:
                neue_set-gruppe:
                  display: 'Neue Set-Gruppe'
                  instructions: null
                  icon: null
                  sets:
                    image:
                      display: Bild
                      instructions: null
                      icon: media-image-picture-orientation
                      fields:
                        -
                          import: image
              type: replicator
              display: Medien
              icon: replicator
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
  work:
    display: Arbeiten
    sections:
      -
        display: Arbeiten
        instructions: 'Text, Medien hinzuf체gen'
        fields:
          -
            handle: work_text
            field:
              buttons:
                - h2
                - bold
                - unorderedlist
                - removeformat
                - anchor
              smart_typography: false
              save_html: false
              inline: false
              toolbar_mode: fixed
              reading_time: false
              word_count: false
              fullscreen: true
              allow_source: true
              enable_input_rules: true
              enable_paste_rules: true
              remove_empty_nodes: false
              antlers: false
              link_noopener: false
              link_noreferrer: false
              target_blank: false
              always_show_set_button: false
              collapse: false
              previews: true
              type: bard
              display: Text
              icon: bard
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: work_media
            field:
              collapse: false
              previews: true
              fullscreen: true
              sets:
                neue_set-gruppe:
                  display: 'Neue Set-Gruppe'
                  instructions: null
                  icon: null
                  sets:
                    image:
                      display: Bild
                      instructions: null
                      icon: media-image-picture-orientation
                      fields:
                        -
                          import: image
              type: replicator
              display: Medien
              icon: replicator
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
  video:
    display: Video
    sections:
      -
        display: Video
        instructions: 'Text/Video hinzuf체gen'
        fields:
          -
            handle: video_text
            field:
              buttons:
                - h2
                - bold
                - unorderedlist
                - removeformat
                - anchor
              smart_typography: false
              save_html: false
              inline: false
              toolbar_mode: fixed
              reading_time: false
              word_count: false
              fullscreen: true
              allow_source: true
              enable_input_rules: true
              enable_paste_rules: true
              remove_empty_nodes: false
              antlers: false
              link_noopener: false
              link_noreferrer: false
              target_blank: false
              always_show_set_button: false
              collapse: false
              previews: true
              type: bard
              display: Text
              icon: bard
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: video_media
            field:
              collapse: false
              previews: true
              fullscreen: true
              sets:
                video:
                  display: Video
                  instructions: null
                  icon: null
                  sets:
                    video:
                      display: Video
                      instructions: null
                      icon: media-webcam-video
                      fields:
                        -
                          import: video
              type: replicator
              display: Medien
              icon: replicator
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: false
              instructions_position: above
              listable: hidden
              visibility: visible
              replicator_preview: true
              input_type: text
              antlers: false
              hide_display: false
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: parent
            field:
              type: entries
              collections:
                - inventory
              max_items: 1
              listable: false
              localizable: true
title: Best채nde
